apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: catalaog-service-pipeline
    name: catalaog-service-pipeline
  name: catalaog-service-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: pipeline
      uri: https://github.com/marzelwidmer/catalog-service.git
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
status:
  lastVersion: 0
