apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: customer-service-pipeline
    name: customer-service-pipeline
  name: customer-service-pipeline
spec:
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/marzelwidmer/customer-service.git
    type: Git
  Source Secret: ci-user-at-github
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile

